export const solfegeNotes = [
  { noteName: "mi4", duration: "4n" },
  { noteName: "re4", duration: "8n" },
  { noteName: "do4", duration: "4n" },
  { noteName: "re4", duration: "8n" },
  { noteName: "mi4", duration: "8n." },
  { noteName: "fa4", duration: "16n" },
  { noteName: "mi4", duration: "8n" },
  { noteName: "re4", duration: "4n." },

  { noteName: "mi4", duration: "4n" },
  { noteName: "re4", duration: "8n" },
  { noteName: "do4", duration: "4n" },
  { noteName: "re4", duration: "8n" },
  { noteName: "mi4", duration: "8n." },
  { noteName: "fa4", duration: "16n" },
  { noteName: "mi4", duration: "8n" },
  { noteName: "re4", duration: "4n." },

  { noteName: "mi4", duration: "4n" },
  { noteName: "re4", duration: "8n" },
  { noteName: "do4", duration: "4n" },
  { noteName: "re4", duration: "8n" },
  { noteName: "mi4", duration: "8n." },
  { noteName: "fa4", duration: "16n" },
  { noteName: "mi4", duration: "8n" },
  { noteName: "re4", duration: "4n." },

  { noteName: "mi4", duration: "4n" },
  { noteName: "re4", duration: "8n" },
  { noteName: "do4", duration: "4n" },
  { noteName: "re4", duration: "8n" },
  { noteName: "mi4", duration: "8n." },
  { noteName: "fa4", duration: "16n" },
  { noteName: "mi4", duration: "8n" },
  { noteName: "re4", duration: "4n." },
];